server:
  port: 9090
  context-path: /terminator
  tomcat:
    basedir: d:/spring-boot

# 管理页面
management:
  security:
    enabled: false

# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terminator
    username: microwise
    password: microwise
    # druid Configuration, url:/terminator/druid/index.html
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # Thymeleaf
  thymeleaf:
    # reload static content
    cache: false

# MyBatis
mybatis:
  type-aliases-package: com.microwise.terminator.sys.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.microwise.terminator.common.persistence.TerminatorMapper
  not-empty: false
  identity: select uuid()
  before: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Flyway
flyway:
  validate-on-migrate: false




# Shiro
shiro:
  loginUrl: /login

#上传图片路径
terminator:
  imagesPath: relic\images\


#环境监控中间件URL
url: http://192.168.3.115:3000/blueplanet-daemon/

#日志路径(默认日志名称spring.log)
logging:
  path: d:/spring-boot

#报警系统URL
tattletaleURL: http://localhost:4000/tattletale/

#系统 systemId ： 1.galaxy 2.terminator 3.eudemon
systemId: 2

#邮件相关配置
smtp:
  host: smtpcloud.sohu.com
  port: 25
  username: postmaster@microwise.sendcloud.org
  password: Y7W32uOpmb8fcP1f












